export interface ToolMetadata {
  id: string;
  title: string;
  metaTitle: string;
  description: string;
  metaDescription: string;
  keywords: string[];
  canonicalUrl: string;
  category: string;
  operatingSystem: string;
  featureList: string[];
  ogImage: string;
  howToSteps: { name: string; text: string }[];
}

export const toolsMetadata: Record<string, ToolMetadata> = {
  compress: {
    id: "compress",
    title: "Compress PDF Online",
    metaTitle: "Compress PDF Online - Target File Size | vibify.tech",
    description: "Compress PDF files to an exact target file size in MB (e.g. 2MB, 500KB) with zero quality compromise.",
    metaDescription: "Compress PDF online to an exact target size in MB (e.g. 2MB or 500KB) on vibify.tech. Free, fast & secure PDF size reducer with zero quality loss.",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf to 2mb", "target size pdf compression", "online pdf compressor", "vibify.tech"],
    canonicalUrl: "https://vibify.tech/tools/compress",
    category: "UtilitiesApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Custom target size MB input",
      "Real-time visual compression preview",
      "Client-side processing with zero server retention",
      "Preserves text clarity and vector graphics",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload PDF", text: "Drag and drop your PDF document or select it from your device." },
      { name: "Set Target Size", text: "Specify your desired target file size in megabytes (MB) or choose a preset." },
      { name: "Compress & Download", text: "Click Compress to process the document and immediately save the optimized PDF." },
    ],
  },
  merge: {
    id: "merge",
    title: "Merge PDF Files Online",
    metaTitle: "Merge PDF Files Online - Combine PDFs Free | vibify.tech",
    description: "Combine multiple PDF documents into a single organized file in seconds. Drag-and-drop page reordering.",
    metaDescription: "Merge and combine multiple PDF files into a single document online for free on vibify.tech. Drag & drop to reorder, fast and secure.",
    keywords: ["merge pdf", "combine pdf", "join pdf files", "merge pdf online", "pdf combiner", "vibify.tech"],
    canonicalUrl: "https://vibify.tech/tools/merge",
    category: "UtilitiesApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Merge unlimited PDF documents",
      "Interactive drag & drop file reordering",
      "Fast in-browser assembly",
      "Privacy-first zero data storage",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Select PDFs", text: "Upload two or more PDF files you want to combine." },
      { name: "Arrange Order", text: "Drag and drop the document cards into your preferred sequence." },
      { name: "Merge & Save", text: "Click Merge PDFs to generate and download your unified document." },
    ],
  },
  ocr: {
    id: "ocr",
    title: "OCR PDF Online - Text Recognition",
    metaTitle: "OCR PDF Online - Extract & Search Text | vibify.tech",
    description: "Recognize and extract text from scanned PDFs and images using high-accuracy optical character recognition.",
    metaDescription: "Run fast OCR text recognition on scanned PDFs and images. Convert scanned documents into searchable, copyable text instantly.",
    keywords: ["ocr pdf", "optical character recognition", "scanned pdf to text", "searchable pdf", "extract text from pdf"],
    canonicalUrl: "https://vibify.tech/tools/ocr",
    category: "BusinessApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "High-precision multilingual text recognition",
      "Searchable PDF & plain text output options",
      "Instant in-browser preview",
      "Secure client-side document processing",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload Scanned Document", text: "Select your scanned PDF or image document." },
      { name: "Run OCR Recognition", text: "Select language preferences and initialize the OCR engine." },
      { name: "Copy or Download", text: "Export the searchable PDF or copy extracted text with one click." },
    ],
  },
  word: {
    id: "word",
    title: "Convert PDF to Word (.docx)",
    metaTitle: "Convert PDF to Word Online (DOCX) | vibify.tech",
    description: "Convert PDF documents to editable Microsoft Word (.docx) files preserving formatting, fonts, and tables.",
    metaDescription: "Convert PDF to Word DOCX documents online for free. Accurate layout preservation and instant editable Word exports.",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word online", "editable pdf to word", "free docx converter"],
    canonicalUrl: "https://vibify.tech/tools/word",
    category: "OfficeApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Faithful preservation of tables, columns, and styles",
      "Outputs standard Microsoft Word (.docx) format",
      "High-speed document conversion",
      "Confidential file handling with auto cleanup",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload PDF Document", text: "Upload the PDF file you wish to edit in Word." },
      { name: "Process Conversion", text: "Our conversion engine extracts paragraphs, headers, and tables." },
      { name: "Download DOCX", text: "Download your fully editable Microsoft Word document." },
    ],
  },
  "add-text": {
    id: "add-text",
    title: "Add Text to PDF Online",
    metaTitle: "Add Text & Annotations to PDF Online | vibify.tech",
    description: "Type, insert, and position custom text anywhere on your PDF pages with customizable fonts, colors, and sizes.",
    metaDescription: "Add custom text, comments, and annotations onto any PDF online. Free interactive visual positioning editor on vibify.tech.",
    keywords: ["add text to pdf", "write on pdf", "edit pdf text", "annotate pdf", "pdf text inserter"],
    canonicalUrl: "https://vibify.tech/tools/add-text",
    category: "DesignApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Draggable text placement anywhere on canvas",
      "Custom font families, sizing, colors, and alignment",
      "Multi-page annotation support",
      "Instant crisp vector PDF download",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload PDF", text: "Load your PDF file into the visual editor." },
      { name: "Add & Position Text", text: "Click to add text boxes, style fonts, and drag to the desired position." },
      { name: "Export Document", text: "Download the updated PDF with your text cleanly rendered." },
    ],
  },
  protect: {
    id: "protect",
    title: "Protect PDF with Password",
    metaTitle: "Protect PDF Online - Password Encryption | vibify.tech",
    description: "Encrypt and lock your sensitive PDF documents with secure 128-bit / 256-bit password protection.",
    metaDescription: "Password protect and encrypt PDF files online for free. Secure your documents with military-grade encryption on vibify.tech.",
    keywords: ["protect pdf", "password protect pdf", "encrypt pdf", "lock pdf file", "secure pdf document"],
    canonicalUrl: "https://vibify.tech/tools/protect",
    category: "SecurityApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Industry-standard password encryption",
      "Restricts unauthorized viewing and printing",
      "Immediate secure file processing",
      "Zero plain-text password storage",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload File", text: "Choose the PDF document you want to secure." },
      { name: "Enter Password", text: "Type a strong encryption password to protect the file." },
      { name: "Download Encrypted PDF", text: "Save your encrypted, password-protected PDF." },
    ],
  },
  unlock: {
    id: "unlock",
    title: "Unlock PDF Online",
    metaTitle: "Unlock PDF Online - Remove Password Protection | vibify.tech",
    description: "Remove passwords and security restrictions from your protected PDF documents quickly and securely.",
    metaDescription: "Unlock PDF files and remove password restrictions online. Fast, secure, and hassle-free PDF decrypter on vibify.tech.",
    keywords: ["unlock pdf", "remove pdf password", "decrypt pdf", "pdf password remover", "unlock protected pdf"],
    canonicalUrl: "https://vibify.tech/tools/unlock",
    category: "SecurityApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Removes owner and user password locks",
      "Restores full editing, printing, and copying permissions",
      "Instant client-side decryption workflow",
      "Guaranteed document integrity",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload Locked PDF", text: "Select your password-protected PDF." },
      { name: "Enter Decryption Key", text: "Provide the authorization password once." },
      { name: "Download Unlocked PDF", text: "Save the unrestricted, permanently unlocked PDF file." },
    ],
  },
  rotate: {
    id: "rotate",
    title: "Rotate PDF Pages Online",
    metaTitle: "Rotate PDF Pages Online - Free Tool | vibify.tech",
    description: "Rotate individual pages or entire PDF documents 90, 180, or 270 degrees clockwise or counterclockwise.",
    metaDescription: "Rotate PDF pages online for free. Fix upside-down or sideways pages with instant visual rotation controls on vibify.tech.",
    keywords: ["rotate pdf", "rotate pdf pages", "flip pdf", "fix upside down pdf", "turn pdf sideways"],
    canonicalUrl: "https://vibify.tech/tools/rotate",
    category: "UtilitiesApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Rotate single pages or all pages simultaneously",
      "Interactive 90° clockwise/counterclockwise orientation buttons",
      "Visual thumbnail preview before saving",
      "Fast lossless page reorientation",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload PDF", text: "Open your PDF document in the rotation studio." },
      { name: "Adjust Orientation", text: "Click the rotate icon on specific pages or choose Rotate All." },
      { name: "Save PDF", text: "Download the freshly oriented PDF document." },
    ],
  },
  delete: {
    id: "delete",
    title: "Delete PDF Pages Online",
    metaTitle: "Delete PDF Pages Online - Remove Pages Free | vibify.tech",
    description: "Remove unwanted, blank, or duplicate pages from any PDF document with visual thumbnail page selection.",
    metaDescription: "Delete specific pages from a PDF online for free. Click to remove unwanted or blank pages and save a clean PDF document.",
    keywords: ["delete pdf pages", "remove pages from pdf", "cut pdf pages", "delete blank pdf pages", "clean pdf document"],
    canonicalUrl: "https://vibify.tech/tools/delete",
    category: "UtilitiesApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Click-to-delete interactive page grid",
      "Bulk page range selector (e.g. 1-3, 5, 8-10)",
      "High-resolution page preview thumbnails",
      "Preserves original PDF bookmarks and structure",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Select PDF Document", text: "Upload the PDF you want to trim." },
      { name: "Select Pages to Remove", text: "Click unwanted pages to mark them for deletion." },
      { name: "Download Clean PDF", text: "Save the document with the selected pages permanently removed." },
    ],
  },
  extract: {
    id: "extract",
    title: "Extract PDF Pages Online",
    metaTitle: "Extract PDF Pages Online - Split PDF Free | vibify.tech",
    description: "Extract specific pages or page ranges from a PDF document into a new standalone PDF file.",
    metaDescription: "Extract pages from PDF online for free. Select custom page ranges or single pages to export into a new PDF document.",
    keywords: ["extract pdf pages", "split pdf", "save selected pdf pages", "pdf page extractor", "separate pdf pages"],
    canonicalUrl: "https://vibify.tech/tools/extract",
    category: "UtilitiesApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Extract individual or custom ranges into a new file",
      "Option to export each page as separate PDF files",
      "Intuitive visual multi-page selection",
      "Preserves embedded fonts, images, and formatting",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload Document", text: "Select the PDF from which you want to extract pages." },
      { name: "Choose Pages", text: "Click the specific pages or enter page numbers to extract." },
      { name: "Download Extracted File", text: "Save your new PDF containing only the chosen pages." },
    ],
  },
  paginate: {
    id: "paginate",
    title: "Add Page Numbers to PDF",
    metaTitle: "Add Page Numbers to PDF Online | vibify.tech",
    description: "Number PDF pages with custom numbering formats (e.g. 'Page 1 of N', roman numerals), positioning, and styles.",
    metaDescription: "Add page numbers to PDF documents online. Customize font, size, position, and numbering style for professional documents.",
    keywords: ["add page numbers to pdf", "paginate pdf", "number pdf pages", "pdf page numbering tool", "bates numbering"],
    canonicalUrl: "https://vibify.tech/tools/paginate",
    category: "UtilitiesApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Custom placement: top/bottom, left/center/right",
      "Multiple formats: 1, 2, 3... Page 1 of N, Roman (i, ii...)",
      "Start numbering on custom page offsets",
      "Real-time visual preview before generation",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload PDF", text: "Choose your PDF document in the pagination studio." },
      { name: "Configure Formatting", text: "Select position, font size, margin, and numbering format." },
      { name: "Download Numbered PDF", text: "Apply numbering and download your paginated document." },
    ],
  },
  archive: {
    id: "archive",
    title: "Convert PDF to PDF/A (Archival)",
    metaTitle: "Convert PDF to PDF/A Online (Archival Standard) | vibify.tech",
    description: "Convert standard PDF documents into ISO-compliant PDF/A files for long-term legal and historical preservation.",
    metaDescription: "Convert PDF to PDF/A online for free. Ensure ISO compliance for long-term document archiving and legal validity.",
    keywords: ["pdf to pdf/a", "pdf archival converter", "iso 19005 compliant pdf", "long term pdf preservation", "pdfa converter"],
    canonicalUrl: "https://vibify.tech/tools/archive",
    category: "BusinessApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "ISO 19005 compliant PDF/A conversion",
      "Embeds missing color profiles and font subsets",
      "Guarantees future visual fidelity and machine readability",
      "Meets legal, government, and archival standards",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Upload PDF File", text: "Select the PDF file you wish to archive." },
      { name: "Select PDF/A Profile", text: "Choose compliance standard (PDF/A-1b, PDF/A-2b)." },
      { name: "Convert & Save", text: "Download your certified archival PDF/A document." },
    ],
  },
  "pdf-maker": {
    id: "pdf-maker",
    title: "Smart PDF Maker Studio",
    metaTitle: "Smart PDF Maker Studio - Create PDFs in Browser | vibify.tech",
    description: "Notion-style block editor to compose, format, style, and instantly export high-quality PDF documents in your browser.",
    metaDescription: "Create rich PDF documents directly in your browser with our Notion-style block editor. Instant PDF and DOCX export with zero software installation.",
    keywords: ["pdf maker", "create pdf online", "notion style pdf editor", "online document maker", "browser pdf creator"],
    canonicalUrl: "https://vibify.tech/tools/pdf-maker",
    category: "DesignApplication",
    operatingSystem: "All (Web Browser)",
    featureList: [
      "Rich block-based document composition",
      "Headings, callouts, tables, checklists, and code blocks",
      "Direct high-resolution vector PDF export",
      "Optional editable Microsoft Word (.docx) export",
    ],
    ogImage: "https://vibify.tech/vibify-og-image.png",
    howToSteps: [
      { name: "Compose Content", text: "Type or paste content using rich block formatting." },
      { name: "Customize Design", text: "Pick fonts, colors, line heights, and margins." },
      { name: "Export Document", text: "Download your publication-ready PDF or Word file instantly." },
    ],
  },
};
